base:
    seed: &seed 42
model:
    type: Llama
    # path: /home/gsb/LLMCMed/abase_models/meta-llama/Meta-Llama-3-8B
    path: /home/gsb/LLMCMed/abase_models/meta-llama/llama-2-7b
    torch_dtype: auto
calib:
    # name: pileval
    name: c4
    download: True
    # path: /home/gsb/LLMCMed/adatasets/processed/pileval
    path: /home/gsb/LLMCMed/adatasets/processed/c4
    n_samples: 128
    # n_samples: 16
    bs: -1
    seq_len: 4096
    preproc: txt_general_preproc
    seed: *seed
    
    # bs: -1
    # download: true
    # n_samples: 128
    # name: wikitext2
    # path: /home/gsb/datasets/processed/wikitext/wikitext-2-v1
    # preproc: wikitext2_gptq
    # seed: 42
    # seq_len: 4096
eval:
    eval_pos: [transformed]
    # eval_pos: []
    name: [wikitext2]
    download: True
    path: /home/gsb/LLMCMed/adatasets/processed/wikitext/wikitext-2-v1
    bs: 1
    seq_len: 4096
sparse:
    method: Wanda
    weight:
        sparsity: 0.50
    special:
        pattern: structured # unstructured, semi_structured, structured
        granularity: channel_wise # channel, group, token, block
        prunen: 4
        prunem: 8
    sparsity_out: False
save:
    save_trans: False
    # save_fake: True
    # save_vllm: True
    # save_path: /home/gsb/LLMCMed/atrans_models/meta-llama/wanda_50_Meta-Llama-3-8B_unstructured
