base:
    seed: &seed 42
model:
    type: Llama
    path:  /home/gsb/LLMCMed/abase_models/meta-llama/Meta-Llama-3-8B
    torch_dtype: auto
eval:
    eval_pos: [pretrain, transformed, fake_quant]
    name: wikitext2
    download: True
    path: /home/gsb/datasets/processed/wikitext/wikitext-2-v1
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Quarot
    weight:
        bit: 8
        symmetric: False
        granularity: per_channel
        group_size: -1
        calib_algo: mse
    act:
        bit: 16
        symmetric: False
        granularity: per_token
    special:
        rotate_mode: hadamard
        fp32_had: True
        online_rotate: True
    modality: language
save:
    # save_trans: True
    save_fake: True
    save_vllm: True
    save_path: /home/gsb/LLMCMed/atrans_models/meta-llama/quarot_w_only_8b_Meta-Llama-3-8B
